# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6967042468e8ae05a8aa3aa4d067a8b405ea9f6bd84692246be0aff04f7011e2372fd586e3ac8ac497430dfb86d2ef9db22750aba08d17525b6a63901e6301e5

test:
  secret_key_base: dd1a73f6b5653e47fda293bf195dac961a2b06c2e9b5be54079e2a8115db88afae5bd84728b3dfc00c71e67b3710e20fc8e6eeea29095f8de5724b2f632ca57d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
